language: go

go:
  - 1.7
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

secure: "CMxB+NS2DLTU7YCTM6np76q1tbN2jT9t0GQBKYWKz5dLaMOgc28MM7se8gU0iG1+4hOf1ixvyKW47pozKWFij1EdHVytPIh5hqSZDIXwiPZToOljzj8T+9A2r8xhFaYZE80wM33X3tluCjTNXTUgMVc5V8eabQQH73VPx5CVGLHxfobuE3ZxznhMVY7RVgxnvwmelpRM/sqBieD/da5LpzGAPIgBeYohuX5oIk/BkSKAnLy8oDkSA5b6lEAH5QyVuhNWabxX3jQpaCvKZLydxHIUiTdAwAua2lmrMJWXQI/9KGl+gzu+ymYMOg0RKnUErmK2Sn8shVoYY4Obl/lijgn7+ofY4+mqGIO48p5d0h4cUJUFWukdSbOBe4/zAAkJibJL3aYrAK5hSm9luXiIb0/NLfo5ZPjUga2i60mMi2svu+U9vuNGcffhkEvWghI09xl69jRMkW/1UnZ8tDgvoMujcF2CIXV6xmveDK9QMEeg4McLrOXv8a6KTDnmFIxIYSJmKbjFfqUurz6USMHEnmuB69zzowrhoBL93oJv3BuNEkAmB2voySZkj6zflxrpAJ2ZGovtcHNj7B02iiCS3Lj6XrkCZc3uemNQ+Wwdq5VPlES8lCSWfiSs/w68MdfNcDLAdQn67jUB8kyX0Jw8p1Loq33VnOk2j9e8zI/GHc8="
